<a href="https://colab.research.google.com/github/oliverZZ/193B_Glucose_Monitor/blob/master/Infection_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline
import warnings
warnings.simplefilter('ignore')
import pandas as pd
pd.options.display.max_rows = 20
import matplotlib.pyplot as plt
import numpy as np

bg = pd.read_excel('/content/drive/My Drive/EEC 193/EEC 193B/Burn_Glucose.xlsx', skiprows = 0)

In [4]:
bg

           PER_CODE Collection Date  Time Vitals  ...  HCO3   PH  Sepsis
0                21      2011-01-02        614.0  ...   NaN  NaN     0.0
1                21      2011-01-03        600.0  ...   NaN  NaN     0.0
2                21      2011-01-04       1000.0  ...   NaN  NaN     0.0
3                21      2011-01-05        930.0  ...   NaN  NaN     0.0
4                21      2011-01-06       1130.0  ...   NaN  NaN     0.0
...             ...             ...          ...  ...   ...  ...     ...
6536  PCR-004-00018      2013-05-27        600.0  ...   NaN  NaN     NaN
6537  PCR-004-00018      2013-05-28        600.0  ...   NaN  NaN     NaN
6538  PCR-004-00018      2013-05-29        600.0  ...   NaN  NaN     NaN
6539  PCR-004-00018      2013-05-30        600.0  ...   NaN  NaN     NaN
6540  PCR-004-00018      2013-05-31        600.0  ...   NaN  NaN     NaN

[6541 rows x 32 columns]

## Data Preprocessing ##

In [0]:
def Drop_nan_row(df):
  
  drop_idx = []
  for i in range(len(df)):
    nan_count = 0
    for x in df.loc[i]:
      if str(x) == 'nan':
        nan_count += 1
    if nan_count >= 15:
      drop_idx.append(i)
    
  modified_df = df.drop(df.index[drop_idx], errors = 'ignore')
  modified_df = modified_df.reset_index(drop = True)

  return modified_df

In [0]:
def Drop_unrelated_cols(df):
  df = df.drop(columns = ['PER_CODE', 'Collection Date', 'Time Vitals', 'Time Labs'], errors = 'ignore')
  return df

In [0]:
def Drop_nan_col(df):
  
  num_rows = len(df)
  for x in df:
    num_nan = 0
    for i in df[x]:
      if str(i) == 'nan':
        num_nan += 1
    
    if (num_nan/num_rows) >= 0.2:
      df = df.drop(columns = x, errors = 'ignore')
  
  return df

In [0]:
def Complete_dataset(df):

  # Change "Yes" and "No" under "Vent" to 1 and 0
  df = df.replace('No', 0)
  df = df.replace('Yes', 1)

  # drop nan or replace them with other value
  df = df.dropna()
  df = df.reset_index(drop = True)

  return df

In [0]:
def data_preprocess(df):

  # drop rows that have too many nan
  df = Drop_nan_row(df)
  # drop times and patient ids
  df = Drop_unrelated_cols(df)
  # drop cols that have too many nan
  df = Drop_nan_col(df)
  # Replace all the other nans
  df = Complete_dataset(df)

  return df

In [0]:
bg = data_preprocess(bg)

In [14]:
bg

      Systolic  Diastolic   MAP     HR  ...  Creatnine  Glucose  Chloride  V_CO2
0        113.0       67.0  78.0  102.0  ...       0.53    110.0     101.0   29.0
1        137.0       67.0  85.0  105.0  ...       0.55    130.0     104.0   27.0
2        124.0       56.0  73.0  104.0  ...       0.53    172.0     103.0   24.0
3        143.0       69.0  85.0  104.0  ...       0.49    150.0     103.0   25.0
4        130.0       59.0  83.0  104.0  ...       0.51    109.0     103.0   27.0
...        ...        ...   ...    ...  ...        ...      ...       ...    ...
5183     138.0       58.0  86.0   98.0  ...       2.44    115.0     115.0   25.0
5184     123.0       63.0  82.0   77.0  ...       0.85     76.0     106.0   25.0
5185     134.0       57.0  76.0  115.0  ...       0.55    252.0     105.0   28.0
5186     106.0       50.0  75.0  134.0  ...       0.57    123.0     101.0   29.0
5187      99.0       45.0  62.0   87.0  ...       1.41    135.0     116.0   24.0

[5188 rows x 20 columns]

## Supervised Learning ##

In [15]:
pip install -U imbalanced-learn

Collecting imbalanced-learn
  Downloading https://files.pythonhosted.org/packages/c8/73/36a13185c2acff44d601dc6107b5347e075561a49e15ddd4e69988414c3e/imbalanced_learn-0.6.2-py3-none-any.whl (163kB)
     |████████████████████████████████| 163kB 2.8MB/s
Requirement already satisfied, skipping upgrade: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from imbalanced-learn) (0.14.1)
Requirement already satisfied, skipping upgrade: scipy>=0.17 in /usr/local/lib/python3.6/dist-packages (from imbalanced-learn) (1.4.1)
Requirement already satisfied, skipping upgrade: scikit-learn>=0.22 in /usr/local/lib/python3.6/dist-packages (from imbalanced-learn) (0.22.1)
Requirement already satisfied, skipping upgrade: numpy>=1.11 in /usr/local/lib/python3.6/dist-packages (from imbalanced-learn) (1.17.5)
Installing collected packages: imbalanced-learn
  Found existing installation: imbalanced-learn 0.4.3
    Uninstalling imbalanced-learn-0.4.3:
      Successfully uninstalled imbalanced-learn-0.4.3
Successfully installed imbalanced-learn-0.6.2

In [16]:
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import classification_report
# from sklearn.preprocessing import RobustScaler
# from sklearn.preprocessing import MinMaxScaler
# from sklearn.preprocessing import StandardScaler
# import imblearn

# x = bg[['RR', 'WBC', 'Glucose', 'Platelet']].values
# y = bg['Sepsis'].values

# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# scaler = RobustScaler()
# x_train = scaler.fit_transform(x_train)
# x_test = scaler.fit_transform(x_test)

# balance = imblearn.over_sampling.SMOTE()
# train_x, train_y = balance.fit_resample(x_train, y_train)
# train_y = pd.Series(train_y)

# model = RandomForestClassifier()
# model.fit(x_train, y_train)
# predictions = model.predict(x_test)

# y_pred = model.predict(x_test)

Using TensorFlow backend.

KeyError: ignored

In [17]:
# print(classification_report(y_test, predictions))

NameError: ignored

## Unsupervised Learning ##