<a href="https://colab.research.google.com/github/oliverZZ/193B_Glucose_Monitor/blob/master/Infection_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline
import warnings
warnings.simplefilter('ignore')
import pandas as pd
pd.options.display.max_rows = 20
import matplotlib.pyplot as plt
import numpy as np

bg = pd.read_excel('/content/drive/My Drive/EEC 193/EEC 193B/Burn_Glucose.xlsx', skiprows = 0)

In [2]:
bg

           PER_CODE Collection Date  Time Vitals  ...  HCO3   PH  Sepsis
0                21      2011-01-02        614.0  ...   NaN  NaN     0.0
1                21      2011-01-03        600.0  ...   NaN  NaN     0.0
2                21      2011-01-04       1000.0  ...   NaN  NaN     0.0
3                21      2011-01-05        930.0  ...   NaN  NaN     0.0
4                21      2011-01-06       1130.0  ...   NaN  NaN     0.0
...             ...             ...          ...  ...   ...  ...     ...
6536  PCR-004-00018      2013-05-27        600.0  ...   NaN  NaN     NaN
6537  PCR-004-00018      2013-05-28        600.0  ...   NaN  NaN     NaN
6538  PCR-004-00018      2013-05-29        600.0  ...   NaN  NaN     NaN
6539  PCR-004-00018      2013-05-30        600.0  ...   NaN  NaN     NaN
6540  PCR-004-00018      2013-05-31        600.0  ...   NaN  NaN     NaN

[6541 rows x 32 columns]

## Data Preprocessing ##

In [0]:
def Drop_many_nan(df):
  
  drop_idx = []
  for i in range(len(df)):
    nan_count = 0
    for x in df.loc[i]:
      if str(x) == 'nan':
        nan_count += 1
    if nan_count >= 15:
      drop_idx.append(i)
    
  modified_df = df.drop(df.index[drop_idx])
  modified_df = modified_df.reset_index(drop = True)

  return modified_df

In [0]:
def data_preprocess(df):

  # drop rows that have too many nan
  df = Drop_many_nan(df)
  

  return df

In [0]:
bg = data_preprocess(bg)

In [13]:
bg

           PER_CODE Collection Date  Time Vitals  ...  HCO3    PH  Sepsis
0                21      2011-01-02        614.0  ...   NaN   NaN     0.0
1                21      2011-01-03        600.0  ...   NaN   NaN     0.0
2                21      2011-01-04       1000.0  ...   NaN   NaN     0.0
3                21      2011-01-05        930.0  ...   NaN   NaN     0.0
4                21      2011-01-06       1130.0  ...   NaN   NaN     0.0
...             ...             ...          ...  ...   ...   ...     ...
5503  PCR-004-00018      2013-05-22        400.0  ...   NaN   NaN     NaN
5504  PCR-004-00018      2013-05-23        600.0  ...  28.0  7.47     NaN
5505  PCR-004-00018      2013-05-24        600.0  ...   NaN   NaN     NaN
5506  PCR-004-00018      2013-05-26        600.0  ...   NaN   NaN     NaN
5507  PCR-004-00018      2013-05-27        600.0  ...   NaN   NaN     NaN

[5508 rows x 32 columns]

In [0]:
pip install -U imbalanced-learn

Requirement already up-to-date: imbalanced-learn in /usr/local/lib/python3.6/dist-packages (0.6.2)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from imbalanced-learn) (0.14.1)
Requirement already satisfied, skipping upgrade: numpy>=1.11 in /usr/local/lib/python3.6/dist-packages (from imbalanced-learn) (1.17.5)
Requirement already satisfied, skipping upgrade: scikit-learn>=0.22 in /usr/local/lib/python3.6/dist-packages (from imbalanced-learn) (0.22.1)
Requirement already satisfied, skipping upgrade: scipy>=0.17 in /usr/local/lib/python3.6/dist-packages (from imbalanced-learn) (1.4.1)

In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
import imblearn

x = bg[['RR', 'WBC', 'Glucose', 'Platelet']].values
y = bg['Sepsis'].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

scaler = RobustScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

balance = imblearn.over_sampling.SMOTE()
train_x, train_y = balance.fit_resample(x_train, y_train)
train_y = pd.Series(train_y)

model = RandomForestClassifier()
model.fit(x_train, y_train)
predictions = model.predict(x_test)

y_pred = model.predict(x_test)

In [0]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.46      0.43      0.44        14
         1.0       0.58      0.61      0.59        18

    accuracy                           0.53        32
   macro avg       0.52      0.52      0.52        32
weighted avg       0.53      0.53      0.53        32